# Generated by Django 4.1 on 2022-09-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_des', models.CharField(max_length=70)),
                ('prod_link', models.URLField()),
                ('prod_rate', models.IntegerField(max_length=20)),
            ],
        ),
    ]
